FROM openjdk:8-jdk

ENV PROJECT_DIR=/app

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

COPY /hzServerNode/target/hzservernode-2.2.1.RELEASE.jar    $PROJECT_DIR/hzservernode.jar

CMD [ "java", "-jar", "hzservernode.jar"]