FROM openjdk:8-jdk

ENV PROJECT_DIR=/app

VOLUME ["/config.configuration"]
VOLUME ["/otus.configurations"]

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

COPY /config/target/config-2.1.3.RELEASE.jar  $PROJECT_DIR/config.jar

CMD [ "java", "-Dspring.config.location=/config.configuration/application.yml", "-jar", "config.jar"]