{
 "title": "Java Micrometer Basics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Sum of Process Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "sum (process_uptime_seconds)" }
   ]
  },
  {
   "title": "Sum of Process CPU Seconds",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Sum of Live Heap Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_gc_live_data_size_bytes)"
    }
   ]
  },
  {
   "title": "Sum of JVM Threads Peak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum (jvm_threads_peak)" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "JVM GC Pause Seconds Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count",
     "legendFormat": "{{action}} / {{cause}} ({{job}})"
    }
   ]
  },
  {
   "title": "JVM GC Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "live ({{job}})" },
    { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "max ({{job}})" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} / {{area}} ({{job}})" }
   ]
  },
  {
   "title": "GC Promoted Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total",
     "legendFormat": " {{job}}"
    }
   ]
  }
 ]
}