spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: authentication

  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled    
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 9999


app:
  jwt:
    signingkey: 123
