spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: hzcatalog


server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled    
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  hazelcast:
    server: hazelcast
    username: dev
    password: dev-pass
  jwt:
    signingkey: 123
  brands:
#    url: http://localhost:8082/microservices/v1/catalog/brands
    ttl: 60
  categories:
#    url: http://localhost:8082/microservices/v1/catalog/categories
    ttl: 60
  warehouses:
#    url: http://localhost:8082/microservices/v1/catalog/warehouses
    ttl: 5
  catalog:
#    url: http://localhost:8082/microservices/v2/catalog
    ttl: 30



