spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com
    password: password
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  rabbitmq:
      host: localhost 
      username: guest # Login user to authenticate to the broker.
      password: guest # Login to authenticate against the broker.
      port: 5672 # RabbitMQ port.

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled    
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


app:
  push:
    account_sid: 11111111111111111111111111111111
    auth_token: 222222222222222222222222222222222
    twilio_number: +1333333333333



  jwt:
    signingkey: 123

