spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    driver-class-name: org.postgresql.Driver
    platform: 
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
      host: localhost 
      username: guest # Login user to authenticate to the broker.
      password: guest # Login to authenticate against the broker.
      port: 5672 # RabbitMQ port.

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled    
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


app:
  jwt:
    signingkey: 123

