spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    mongodb:
      host: localhost
      database: chat
      port: 27017

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled    
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    signingkey: 123
