spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: notification

  datasource:
    url: jdbc:postgresql://postgres:5432/eshop
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  rabbitmq:
    host: rabbit
    username: guest # Login user to authenticate to the broker.
    password: guest # Login to authenticate against the broker.
    port: 5672 # RabbitMQ port.


  mail:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com
    password: password
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

app:
  push:
    account_sid: ACffb38145b9c140cbcbff160dc18bfd1e
    auth_token: 33480ce54329c95467b57dceda3e6d07
    twilio_number: +12403292300

  jwt:
    signingkey: 123

