spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:postgresql://postgres:5432/eshop
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
                 
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, logfile, metrics, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus: enabled    
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 

app:
  jwt:
    signingkey: 123
